export interface BirdAudio {
  xcId: string;
  file: string;
  recordist: string;
  license: string;
  licenseUrl: string;
  xcUrl: string;
}

export const birdAudio: Record<string, BirdAudio> = {
  "Cyanocorax yncas": {
    xcId: "797052",
    file: "https://xeno-canto.org/sounds/uploaded/RJNSQXBIJE/XC797052-2.-Cyanocorax-yncas-XC-listo.mp3",
    recordist: "Leonardo Ordóñez-Delgado",
    license: "CC BY-NC-ND 4.0",
    licenseUrl: "https://creativecommons.org/licenses/by-nc-nd/4.0/",
    xcUrl: "https://www.xeno-canto.org/797052",
  },
  "Icterus gularis": {
    xcId: "956290",
    file: "https://xeno-canto.org/sounds/uploaded/ZWAQHOJFLZ/XC956290-241101-Oriole-a%CC%80-gros-bec%40Huatulco.mp3",
    recordist: "Étienne Leroy",
    license: "CC BY-NC-SA 4.0",
    licenseUrl: "https://creativecommons.org/licenses/by-nc-sa/4.0/",
    xcUrl: "https://www.xeno-canto.org/956290",
  },
  "Ortalis vetula": {
    xcId: "1027735",
    file: "https://xeno-canto.org/sounds/uploaded/NYTGVXSILH/XC1027735-Plain-Chachalaca---Chajbaoc,-AV,-GT---2025-07-24-735 AM.mp3",
    recordist: "Max Noack",
    license: "CC BY-NC-SA 4.0",
    licenseUrl: "https://creativecommons.org/licenses/by-nc-sa/4.0/",
    xcUrl: "https://www.xeno-canto.org/1027735",
  },
  "Amazilia yucatanensis": {
    xcId: "809646",
    file: "https://xeno-canto.org/sounds/uploaded/ILUHRFXDNU/XC809646-Buff-bellied-Hummingbird-calls-paraiso-jun-18-615-DR0000_1089.mp3",
    recordist: "Manuel Grosselet",
    license: "CC BY-NC-SA 4.0",
    licenseUrl: "https://creativecommons.org/licenses/by-nc-sa/4.0/",
    xcUrl: "https://www.xeno-canto.org/809646",
  },
  "Passerina ciris": {
    xcId: "1087845",
    file: "https://xeno-canto.org/sounds/uploaded/PVQOLRXXWL/XC1087845-Painted-Bunting-male-song-at-Peveto-Woods-LA-5.3.23-at-16.03-for-.42.mp3",
    recordist: "Sue Riffe",
    license: "CC BY-NC-SA 4.0",
    licenseUrl: "https://creativecommons.org/licenses/by-nc-sa/4.0/",
    xcUrl: "https://www.xeno-canto.org/1087845",
  },
  "Platalea ajaja": {
    xcId: "623963",
    file: "https://xeno-canto.org/sounds/uploaded/ILUHRFXDNU/XC623963-Roseate%20Spoonbill%20CAlls%20Union%20Hildalgo%20Feb%2018%20631_1758.mp3",
    recordist: "Manuel Grosselet",
    license: "CC BY-NC-SA 4.0",
    licenseUrl: "https://creativecommons.org/licenses/by-nc-sa/4.0/",
    xcUrl: "https://www.xeno-canto.org/623963",
  },
  "Grus americana": {
    xcId: "533637",
    file: "https://xeno-canto.org/sounds/uploaded/PVQOLRXXWL/XC533637-Whooping%20Cranes%20at%20Backbone%20Rd%20Polk%20Cty%20FL%20on%201.5.20%20at%207.51%20for%20.39.mp3",
    recordist: "Sue Riffe",
    license: "CC BY-NC-SA 4.0",
    licenseUrl: "https://creativecommons.org/licenses/by-nc-sa/4.0/",
    xcUrl: "https://www.xeno-canto.org/533637",
  },
  "Caracara plancus": {
    xcId: "823554",
    file: "https://xeno-canto.org/sounds/uploaded/LXKLWEDKEM/XC823554-17-08-2023-7e52-Carcara-TAQUARAL.mp3",
    recordist: "JAYRSON ARAUJO DE OLIVEIRA",
    license: "CC BY-NC-SA 4.0",
    licenseUrl: "https://creativecommons.org/licenses/by-nc-sa/4.0/",
    xcUrl: "https://www.xeno-canto.org/823554",
  },
  "Parabuteo unicinctus": {
    xcId: "875607",
    file: "https://xeno-canto.org/sounds/uploaded/VLDFGFKOWN/XC875607-Gavilanmixto12.05pmBosqueConstituyentes11deFebrero.mp3",
    recordist: "Franco Vushurovich",
    license: "CC BY-NC-SA 4.0",
    licenseUrl: "https://creativecommons.org/licenses/by-nc-sa/4.0/",
    xcUrl: "https://www.xeno-canto.org/875607",
  },
  "Falco femoralis": {
    xcId: "83324",
    file: "https://xeno-canto.org/sounds/uploaded/QTNGUZTTQM/FLF_Falco_femoralis.mp3",
    recordist: "Fernando Fávaro",
    license: "CC BY-NC-ND 2.5",
    licenseUrl: "https://creativecommons.org/licenses/by-nc-nd/2.5/",
    xcUrl: "https://www.xeno-canto.org/83324",
  },
  "Buteo platypterus": {
    xcId: "1056117",
    file: "https://xeno-canto.org/sounds/uploaded/SMUORWOKLJ/XC1056117-Petite-buse.mp3",
    recordist: "Denis Dujardin",
    license: "CC BY-NC-SA 4.0",
    licenseUrl: "https://creativecommons.org/licenses/by-nc-sa/4.0/",
    xcUrl: "https://www.xeno-canto.org/1056117",
  },
  "Buteo plagiatus": {
    xcId: "625830",
    file: "https://xeno-canto.org/sounds/uploaded/KZYUWIRZVH/XC625830-HAWK_Gray_s_wail%201x%20SBNWR%201100m%20082120%201006.mp3",
    recordist: "Richard E. Webster",
    license: "CC BY-NC-SA 4.0",
    licenseUrl: "https://creativecommons.org/licenses/by-nc-sa/4.0/",
    xcUrl: "https://www.xeno-canto.org/625830",
  },
  "Chondrohierax uncinatus": {
    xcId: "1012062",
    file: "https://xeno-canto.org/sounds/uploaded/BBFFGHPZZQ/XC1012062-Chondrohierax-uncinatus.mp3",
    recordist: "Manuel Sánchez-Nivicela",
    license: "CC BY-NC-ND 4.0",
    licenseUrl: "https://creativecommons.org/licenses/by-nc-nd/4.0/",
    xcUrl: "https://www.xeno-canto.org/1012062",
  },
  "Megaceryle torquata": {
    xcId: "1090536",
    file: "https://xeno-canto.org/sounds/uploaded/LXKLWEDKEM/XC1090536-20-03-2026-8e31-Martim-pescador-grande-SERRA-DA-MESA.mp3",
    recordist: "JAYRSON ARAUJO DE OLIVEIRA",
    license: "CC BY-NC-SA 4.0",
    licenseUrl: "https://creativecommons.org/licenses/by-nc-sa/4.0/",
    xcUrl: "https://www.xeno-canto.org/1090536",
  },
  "Chloroceryle americana": {
    xcId: "516956",
    file: "https://xeno-canto.org/sounds/uploaded/WETAASKWUP/XC516956-Green%20Kingfisher.mp3",
    recordist: "Jacob Wijpkema",
    license: "CC BY-NC-SA 4.0",
    licenseUrl: "https://creativecommons.org/licenses/by-nc-sa/4.0/",
    xcUrl: "https://www.xeno-canto.org/516956",
  },
  "Pyrocephalus rubinus": {
    xcId: "871819",
    file: "https://xeno-canto.org/sounds/uploaded/HLHEJPMMIW/XC871819-Churrinche-en-El-Marquesado---Buenos-Aires%2C-Argentina.mp3",
    recordist: "María Emilia Pérez",
    license: "CC BY-NC-SA 4.0",
    licenseUrl: "https://creativecommons.org/licenses/by-nc-sa/4.0/",
    xcUrl: "https://www.xeno-canto.org/871819",
  },
  "Pitangus sulphuratus": {
    xcId: "1140118",
    file: "https://xeno-canto.org/sounds/uploaded/YTUXOCTUEM/XC1140118-Great-Kiskidee-FL-song-Finca-Pastora-Reserva-Petevca-5Nov22-2.58p-LS117247a.mp3",
    recordist: "Frank Lambert",
    license: "CC BY-NC-ND 4.0",
    licenseUrl: "https://creativecommons.org/licenses/by-nc-nd/4.0/",
    xcUrl: "https://www.xeno-canto.org/1140118",
  },
  "Tyrannus melancholicus": {
    xcId: "1142508",
    file: "https://xeno-canto.org/sounds/uploaded/BBFFGHPZZQ/XC1142508-Tropical_Kingbird.mp3",
    recordist: "Manuel Sánchez-Nivicela",
    license: "CC BY-NC-ND 4.0",
    licenseUrl: "https://creativecommons.org/licenses/by-nc-nd/4.0/",
    xcUrl: "https://www.xeno-canto.org/1142508",
  },
  "Glaucidium brasilianum": {
    xcId: "1137639",
    file: "https://xeno-canto.org/sounds/uploaded/HJPHFPKHXV/XC1137639-g_brasilianum_01.mp3",
    recordist: "Franciel da Silva Lima",
    license: "CC BY-NC-ND 4.0",
    licenseUrl: "https://creativecommons.org/licenses/by-nc-nd/4.0/",
    xcUrl: "https://www.xeno-canto.org/1137639",
  },
  "Micrathene whitneyi": {
    xcId: "1138696",
    file: "https://xeno-canto.org/sounds/uploaded/RFTXRYBVBX/XC1138696--03455-Elf-Owl--AZ,-Box-Canyon-Rd,-May-20,-2026,-0906-PM-edited.mp3",
    recordist: "Paul Marvin",
    license: "CC BY-NC-SA 4.0",
    licenseUrl: "https://creativecommons.org/licenses/by-nc-sa/4.0/",
    xcUrl: "https://www.xeno-canto.org/1138696",
  },
  "Tachybaptus dominicus": {
    xcId: "817508",
    file: "https://xeno-canto.org/sounds/uploaded/ILUHRFXDNU/XC817508-Least-grebe-calls-gendulain-jul-17-755-DR0000_1318.mp3",
    recordist: "Manuel Grosselet",
    license: "CC BY-NC-SA 4.0",
    licenseUrl: "https://creativecommons.org/licenses/by-nc-sa/4.0/",
    xcUrl: "https://www.xeno-canto.org/817508",
  },
  "Dendrocygna autumnalis": {
    xcId: "920149",
    file: "https://xeno-canto.org/sounds/uploaded/UTXSVIHVRJ/XC920149-dendro080724-065919.mp3",
    recordist: "Leonardo Guzman Hernandez",
    license: "CC BY-NC-SA 4.0",
    licenseUrl: "https://creativecommons.org/licenses/by-nc-sa/4.0/",
    xcUrl: "https://www.xeno-canto.org/920149",
  },
  "Nomonyx dominicus": {
    xcId: "770310",
    file: "https://xeno-canto.org/sounds/uploaded/CHDHFSVVIN/XC770310-Nomonyx-dominicus%28song-in-rp%292022_12_04_18Rhodia_PauliniaSP.mp3",
    recordist: "Fernando Igor de Godoy",
    license: "CC BY-NC-SA 4.0",
    licenseUrl: "https://creativecommons.org/licenses/by-nc-sa/4.0/",
    xcUrl: "https://www.xeno-canto.org/770310",
  },
  "Jacana spinosa": {
    xcId: "880857",
    file: "https://xeno-canto.org/sounds/uploaded/LHHZWGIPDV/XC880857-Jacana-spinosa-20240309-Chinameca.mp3",
    recordist: "Homero Bennet",
    license: "CC BY-NC-SA 4.0",
    licenseUrl: "https://creativecommons.org/licenses/by-nc-sa/4.0/",
    xcUrl: "https://www.xeno-canto.org/880857",
  },
  "Crotophaga sulcirostris": {
    xcId: "956278",
    file: "https://xeno-canto.org/sounds/uploaded/ZWAQHOJFLZ/XC956278-241030-Ani-a%CC%80-bec-cannele%CC%81%40Santiago-Cuixtla.mp3",
    recordist: "Étienne Leroy",
    license: "CC BY-NC-SA 4.0",
    licenseUrl: "https://creativecommons.org/licenses/by-nc-sa/4.0/",
    xcUrl: "https://www.xeno-canto.org/956278",
  },
  "Turdus grayi": {
    xcId: "1106457",
    file: "https://xeno-canto.org/sounds/uploaded/DUWDSSWZPN/XC1106457-2026.03.22_05.08.54_Clay-colored-Thrush.mp3",
    recordist: "Bill Pyle",
    license: "CC BY-NC-SA 4.0",
    licenseUrl: "https://creativecommons.org/licenses/by-nc-sa/4.0/",
    xcUrl: "https://www.xeno-canto.org/1106457",
  },
  "Toxostoma longirostre": {
    xcId: "1078781",
    file: "https://xeno-canto.org/sounds/uploaded/WEFETQLIEQ/XC1078781-2017-05-16---07h40---Long-billed-Thrasher-%28song%29.mp3",
    recordist: "Joren van Schie",
    license: "CC BY-NC-SA 4.0",
    licenseUrl: "https://creativecommons.org/licenses/by-nc-sa/4.0/",
    xcUrl: "https://www.xeno-canto.org/1078781",
  },
  "Icterus graduacauda": {
    xcId: "997858",
    file: "https://xeno-canto.org/sounds/uploaded/ILUHRFXDNU/XC997858-Dickey-s-Oriole-Song-SPE-May-12-821-DR0000_2478.mp3",
    recordist: "Manuel Grosselet",
    license: "CC BY-NC-SA 4.0",
    licenseUrl: "https://creativecommons.org/licenses/by-nc-sa/4.0/",
    xcUrl: "https://www.xeno-canto.org/997858",
  },
  "Arremonops rufivirgatus": {
    xcId: "1025798",
    file: "https://xeno-canto.org/sounds/uploaded/ILUHRFXDNU/XC1025798-Olive-Sparrow-jacatepec-jul-20-621-DR0000_2656.mp3",
    recordist: "Manuel Grosselet",
    license: "CC BY-NC-SA 4.0",
    licenseUrl: "https://creativecommons.org/licenses/by-nc-sa/4.0/",
    xcUrl: "https://www.xeno-canto.org/1025798",
  },
  "Leptotila verreauxi": {
    xcId: "1141175",
    file: "https://xeno-canto.org/sounds/uploaded/YTUXOCTUEM/XC1141175-White-tipped-Dove-nom-FL-X-song-Guaviare-R-nr-Inirida17Oct22-10.07a-LS116737a.mp3",
    recordist: "Frank Lambert",
    license: "CC BY-NC-ND 4.0",
    licenseUrl: "https://creativecommons.org/licenses/by-nc-nd/4.0/",
    xcUrl: "https://www.xeno-canto.org/1141175",
  },
  "Egretta rufescens": {
    xcId: "568815",
    file: "https://xeno-canto.org/sounds/uploaded/VCRVBXOHTS/XC568815-200615_0160%20REEG%2C%20WIPL%2C%20amoy%2C%20call%20paredones%20sin.mp3",
    recordist: "Isain Contreras Rodríguez",
    license: "CC BY-NC-SA 4.0",
    licenseUrl: "https://creativecommons.org/licenses/by-nc-sa/4.0/",
    xcUrl: "https://www.xeno-canto.org/568815",
  },
  "Egretta tricolor": {
    xcId: "705371",
    file: "https://xeno-canto.org/sounds/uploaded/FSCGENVPXK/XC705371-TRICOLORED%20HERON%20%20Big%20Cypress%20NR%20FL%207.34am%20%2002262022%20.mp3",
    recordist: "Paul Driver",
    license: "CC BY-NC-SA 4.0",
    licenseUrl: "https://creativecommons.org/licenses/by-nc-sa/4.0/",
    xcUrl: "https://www.xeno-canto.org/705371",
  },
  "Nannopterum brasilianum": {
    xcId: "993768",
    file: "https://xeno-canto.org/sounds/uploaded/UZCHJCUDEF/XC993768-Phalacrocorax-brasilianus-ZOOM0001.mp3",
    recordist: "Guillermo Treboux",
    license: "CC BY-NC-SA 4.0",
    licenseUrl: "https://creativecommons.org/licenses/by-nc-sa/4.0/",
    xcUrl: "https://www.xeno-canto.org/993768",
  },
  "Geranoaetus albicaudatus": {
    xcId: "832952",
    file: "https://xeno-canto.org/sounds/uploaded/LXKLWEDKEM/XC832952-28-09-2023-14e52-Gaviao-de-rabo-branco-PARACATU.mp3",
    recordist: "JAYRSON ARAUJO DE OLIVEIRA",
    license: "CC BY-NC-SA 4.0",
    licenseUrl: "https://creativecommons.org/licenses/by-nc-sa/4.0/",
    xcUrl: "https://www.xeno-canto.org/832952",
  },
  "Elanus leucurus": {
    xcId: "987852",
    file: "https://xeno-canto.org/sounds/uploaded/FPXOZOPHTA/XC987852-250413_5827-White-tailed-Kite-(song).mp3",
    recordist: "José María Loaiza B.",
    license: "CC BY-NC-SA 4.0",
    licenseUrl: "https://creativecommons.org/licenses/by-nc-sa/4.0/",
    xcUrl: "https://www.xeno-canto.org/987852",
  },
  "Elanoides forficatus": {
    xcId: "844661",
    file: "https://xeno-canto.org/sounds/uploaded/PVWSUUVNDA/XC844661-G.-tesoura.mp3",
    recordist: "Mateus Gonçalves Santos",
    license: "CC BY-NC-SA 4.0",
    licenseUrl: "https://creativecommons.org/licenses/by-nc-sa/4.0/",
    xcUrl: "https://www.xeno-canto.org/844661",
  },
  "Tyrannus couchii": {
    xcId: "896087",
    file: "https://xeno-canto.org/sounds/uploaded/ILUHRFXDNU/XC896087-Couch-s-Kingbird-song-plan-de-flores-Oaxa-apr-13-1602--DR0000_1810.mp3",
    recordist: "Manuel Grosselet",
    license: "CC BY-NC-SA 4.0",
    licenseUrl: "https://creativecommons.org/licenses/by-nc-sa/4.0/",
    xcUrl: "https://www.xeno-canto.org/896087",
  },
  "Tyrannus forficatus": {
    xcId: "323788",
    file: "https://xeno-canto.org/sounds/uploaded/VREQOVRYQI/XC323788-08stfl06011513.mp3",
    recordist: "Terry Davis",
    license: "CC BY-NC-SA 4.0",
    licenseUrl: "https://creativecommons.org/licenses/by-nc-sa/4.0/",
    xcUrl: "https://www.xeno-canto.org/323788",
  },
  "Pachyramphus aglaiae": {
    xcId: "791888",
    file: "https://xeno-canto.org/sounds/uploaded/NYTGVXSILH/XC791888-Rose-throated-Becard---Chajbaoc%2C-AV%2C-GT-%282023-04%29.mp3",
    recordist: "Max Noack",
    license: "CC BY-NC-SA 4.0",
    licenseUrl: "https://creativecommons.org/licenses/by-nc-sa/4.0/",
    xcUrl: "https://www.xeno-canto.org/791888",
  },
  "Patagioenas flavirostris": {
    xcId: "927187",
    file: "https://xeno-canto.org/sounds/uploaded/KZYUWIRZVH/XC927187-PIGEON_Red-bil-PB-Hagia-Sofia-300m-062224-0746.mp3",
    recordist: "Richard E. Webster",
    license: "CC BY-NC-SA 4.0",
    licenseUrl: "https://creativecommons.org/licenses/by-nc-sa/4.0/",
    xcUrl: "https://www.xeno-canto.org/927187",
  },
  "Columbina inca": {
    xcId: "1092842",
    file: "https://xeno-canto.org/sounds/uploaded/ILUHRFXDNU/XC1092842-Inca-Dove-la-mancha-apr-1-752-DR0000_3373.mp3",
    recordist: "Manuel Grosselet",
    license: "CC BY-NC-SA 4.0",
    licenseUrl: "https://creativecommons.org/licenses/by-nc-sa/4.0/",
    xcUrl: "https://www.xeno-canto.org/1092842",
  },
  "Geococcyx californianus": {
    xcId: "884929",
    file: "https://xeno-canto.org/sounds/uploaded/TMEDMAITLF/XC884929-Greater-Roadrunner---Love-Creek-Preserve-03-02-2024.mp3",
    recordist: "Mark McClelland",
    license: "CC BY-NC-SA 4.0",
    licenseUrl: "https://creativecommons.org/licenses/by-nc-sa/4.0/",
    xcUrl: "https://www.xeno-canto.org/884929",
  },
  "Haematopus palliatus": {
    xcId: "565541",
    file: "https://xeno-canto.org/sounds/uploaded/MGVGHKBMIZ/XC565541-OysterCatcher2.mp3",
    recordist: "William Whitehead",
    license: "CC BY-NC-SA 4.0",
    licenseUrl: "https://creativecommons.org/licenses/by-nc-sa/4.0/",
    xcUrl: "https://www.xeno-canto.org/565541",
  },
  "Psittacara holochlorus": {
    xcId: "913394",
    file: "https://xeno-canto.org/sounds/uploaded/ILUHRFXDNU/XC913394-Green-parakeet-chicks-and-adult-la-esmeralda-jun11-853-DR0000_1982.mp3",
    recordist: "Manuel Grosselet",
    license: "CC BY-NC-SA 4.0",
    licenseUrl: "https://creativecommons.org/licenses/by-nc-sa/4.0/",
    xcUrl: "https://www.xeno-canto.org/913394",
  },
  "Amazona viridigenalis": {
    xcId: "309802",
    file: "https://xeno-canto.org/sounds/uploaded/ILUHRFXDNU/XC309802-red-crowned%20parrot.mp3",
    recordist: "Manuel Grosselet",
    license: "CC BY-NC-SA 4.0",
    licenseUrl: "https://creativecommons.org/licenses/by-nc-sa/4.0/",
    xcUrl: "https://www.xeno-canto.org/309802",
  },
  "Sporophila morelleti": {
    xcId: "1035686",
    file: "https://xeno-canto.org/sounds/uploaded/YHKQPPJDVP/XC1035686-250302_2483MOSE-10M-MP3-AMP.mp3",
    recordist: "Bobby Wilcox",
    license: "CC BY-NC-SA 4.0",
    licenseUrl: "https://creativecommons.org/licenses/by-nc-sa/4.0/",
    xcUrl: "https://www.xeno-canto.org/1035686",
  },
  "Setophaga pitiayumi": {
    xcId: "1143054",
    file: "https://xeno-canto.org/sounds/uploaded/DWSIIBXQEQ/XC1143054-tropical-parula.mp3",
    recordist: "Marcos E. Sosa",
    license: "CC BY-NC-SA 4.0",
    licenseUrl: "https://creativecommons.org/licenses/by-nc-sa/4.0/",
    xcUrl: "https://www.xeno-canto.org/1143054",
  },
  "Anas fulvigula": {
    xcId: "192343",
    file: "https://xeno-canto.org/sounds/uploaded/RFTXRYBVBX/XC192343-Mottled%20Duck%20male%2C%20looked%20pure%2C%20yellow%20bill%2C%20straight%20tail%20not%20white%20-FL%2C%20MINWR%2C%20Peacock%27a%20Pocket%20Rd%20%2C%20April%2010%2C%202014%2C%201127%20AM.mp3",
    recordist: "Paul Marvin",
    license: "CC BY-NC-SA 4.0",
    licenseUrl: "https://creativecommons.org/licenses/by-nc-sa/4.0/",
    xcUrl: "https://www.xeno-canto.org/192343",
  },
  "Charadrius melodus": {
    xcId: "738566",
    file: "https://xeno-canto.org/sounds/uploaded/MGVGHKBMIZ/XC738566-PipingPlover4.mp3",
    recordist: "William Whitehead",
    license: "CC BY-NC-ND 4.0",
    licenseUrl: "https://creativecommons.org/licenses/by-nc-nd/4.0/",
    xcUrl: "https://www.xeno-canto.org/738566",
  },
  "Peucaea botterii": {
    xcId: "1036622",
    file: "https://xeno-canto.org/sounds/uploaded/ILUHRFXDNU/XC1036622-Botteri-s-Sparrow-Rojas-Sept-6-838DR0000_2810.mp3",
    recordist: "Manuel Grosselet",
    license: "CC BY-NC-SA 4.0",
    licenseUrl: "https://creativecommons.org/licenses/by-nc-sa/4.0/",
    xcUrl: "https://www.xeno-canto.org/1036622",
  },
};
