export const BIRDS_ORDER: { name: string; slug: string }[] = [
  { name: "Green Jay",                     slug: "green-jay" },
  { name: "Altamira Oriole",               slug: "altamira-oriole" },
  { name: "Plain Chachalaca",              slug: "plain-chachalaca" },
  { name: "Buff-bellied Hummingbird",      slug: "buff-bellied-hummingbird" },
  { name: "Painted Bunting",               slug: "painted-bunting" },
  { name: "Roseate Spoonbill",             slug: "roseate-spoonbill" },
  { name: "Whooping Crane",                slug: "whooping-crane" },
  { name: "Crested Caracara",              slug: "crested-caracara" },
  { name: "Harris's Hawk",                 slug: "harriss-hawk" },
  { name: "Aplomado Falcon",               slug: "aplomado-falcon" },
  { name: "Broad-winged Hawk",             slug: "broad-winged-hawk" },
  { name: "Gray Hawk",                     slug: "gray-hawk" },
  { name: "Hook-billed Kite",              slug: "hook-billed-kite" },
  { name: "Ringed Kingfisher",             slug: "ringed-kingfisher" },
  { name: "Green Kingfisher",              slug: "green-kingfisher" },
  { name: "Vermilion Flycatcher",          slug: "vermilion-flycatcher" },
  { name: "Great Kiskadee",               slug: "great-kiskadee" },
  { name: "Tropical Kingbird",             slug: "tropical-kingbird" },
  { name: "Ferruginous Pygmy-Owl",         slug: "ferruginous-pygmy-owl" },
  { name: "Elf Owl",                       slug: "elf-owl" },
  { name: "Least Grebe",                   slug: "least-grebe" },
  { name: "Black-bellied Whistling-Duck",  slug: "black-bellied-whistling-duck" },
  { name: "Masked Duck",                   slug: "masked-duck" },
  { name: "Northern Jacana",               slug: "northern-jacana" },
  { name: "Groove-billed Ani",             slug: "groove-billed-ani" },
  { name: "Clay-colored Thrush",           slug: "clay-colored-thrush" },
  { name: "Long-billed Thrasher",          slug: "long-billed-thrasher" },
  { name: "Audubon's Oriole",              slug: "audubons-oriole" },
  { name: "Olive Sparrow",                 slug: "olive-sparrow" },
  { name: "White-tipped Dove",             slug: "white-tipped-dove" },
  { name: "Reddish Egret",                 slug: "reddish-egret" },
  { name: "Tricolored Heron",              slug: "tricolored-heron" },
  { name: "Neotropic Cormorant",           slug: "neotropic-cormorant" },
  { name: "White-tailed Hawk",             slug: "white-tailed-hawk" },
  { name: "White-tailed Kite",             slug: "white-tailed-kite" },
  { name: "Swallow-tailed Kite",           slug: "swallow-tailed-kite" },
  { name: "Couch's Kingbird",              slug: "couchs-kingbird" },
  { name: "Scissor-tailed Flycatcher",     slug: "scissor-tailed-flycatcher" },
  { name: "Rose-throated Becard",          slug: "rose-throated-becard" },
  { name: "Red-billed Pigeon",             slug: "red-billed-pigeon" },
  { name: "Inca Dove",                     slug: "inca-dove" },
  { name: "Greater Roadrunner",            slug: "greater-roadrunner" },
  { name: "American Oystercatcher",        slug: "american-oystercatcher" },
  { name: "Green Parakeet",                slug: "green-parakeet" },
  { name: "Red-crowned Parrot",            slug: "red-crowned-parrot" },
  { name: "White-collared Seedeater",      slug: "white-collared-seedeater" },
  { name: "Tropical Parula",               slug: "tropical-parula" },
  { name: "Mottled Duck",                  slug: "mottled-duck" },
  { name: "Piping Plover",                 slug: "piping-plover" },
  { name: "Botteri's Sparrow",             slug: "botteris-sparrow" },
];

export const toBirdId = (name: string): string =>
  name.toLowerCase().replace(/[''']/g, "").replace(/[^a-z0-9]+/g, "-").replace(/^-|-$/g, "");

export const RELATED_SPECIES: Record<string, string[]> = {
  // Jay / South Texas thornscrub icons
  "green-jay":                   ["altamira-oriole", "plain-chachalaca", "groove-billed-ani"],
  "altamira-oriole":             ["audubons-oriole", "green-jay", "great-kiskadee"],
  "audubons-oriole":             ["altamira-oriole", "long-billed-thrasher", "olive-sparrow"],
  "plain-chachalaca":            ["green-jay", "groove-billed-ani", "greater-roadrunner"],
  // Hummingbird / garden birds
  "buff-bellied-hummingbird":    ["painted-bunting", "vermilion-flycatcher", "inca-dove"],
  "painted-bunting":             ["buff-bellied-hummingbird", "vermilion-flycatcher", "scissor-tailed-flycatcher"],
  // Raptors
  "crested-caracara":            ["harriss-hawk", "aplomado-falcon", "white-tailed-hawk"],
  "harriss-hawk":                ["crested-caracara", "aplomado-falcon", "gray-hawk"],
  "aplomado-falcon":             ["crested-caracara", "harriss-hawk", "white-tailed-hawk"],
  "broad-winged-hawk":           ["gray-hawk", "hook-billed-kite", "harriss-hawk"],
  "gray-hawk":                   ["broad-winged-hawk", "hook-billed-kite", "harriss-hawk"],
  "hook-billed-kite":            ["white-tailed-kite", "swallow-tailed-kite", "gray-hawk"],
  "white-tailed-hawk":           ["crested-caracara", "aplomado-falcon", "harriss-hawk"],
  "white-tailed-kite":           ["swallow-tailed-kite", "hook-billed-kite", "white-tailed-hawk"],
  "swallow-tailed-kite":         ["white-tailed-kite", "hook-billed-kite", "broad-winged-hawk"],
  // Owls
  "ferruginous-pygmy-owl":       ["elf-owl", "greater-roadrunner", "green-jay"],
  "elf-owl":                     ["ferruginous-pygmy-owl", "groove-billed-ani", "greater-roadrunner"],
  // Kingfishers
  "ringed-kingfisher":           ["green-kingfisher", "neotropic-cormorant", "least-grebe"],
  "green-kingfisher":            ["ringed-kingfisher", "least-grebe", "neotropic-cormorant"],
  // Flycatchers / kingbirds
  "vermilion-flycatcher":        ["scissor-tailed-flycatcher", "couchs-kingbird", "rose-throated-becard"],
  "great-kiskadee":              ["tropical-kingbird", "couchs-kingbird", "rose-throated-becard"],
  "tropical-kingbird":           ["couchs-kingbird", "great-kiskadee", "scissor-tailed-flycatcher"],
  "couchs-kingbird":             ["tropical-kingbird", "great-kiskadee", "vermilion-flycatcher"],
  "scissor-tailed-flycatcher":   ["vermilion-flycatcher", "couchs-kingbird", "tropical-kingbird"],
  "rose-throated-becard":        ["great-kiskadee", "tropical-kingbird", "vermilion-flycatcher"],
  // Wading birds
  "roseate-spoonbill":           ["reddish-egret", "tricolored-heron", "whooping-crane"],
  "reddish-egret":               ["tricolored-heron", "roseate-spoonbill", "neotropic-cormorant"],
  "tricolored-heron":            ["reddish-egret", "roseate-spoonbill", "neotropic-cormorant"],
  "whooping-crane":              ["roseate-spoonbill", "mottled-duck", "piping-plover"],
  // Ducks / waterbirds
  "black-bellied-whistling-duck":["masked-duck", "mottled-duck", "least-grebe"],
  "masked-duck":                 ["black-bellied-whistling-duck", "mottled-duck", "northern-jacana"],
  "mottled-duck":                ["black-bellied-whistling-duck", "masked-duck", "piping-plover"],
  "least-grebe":                 ["neotropic-cormorant", "northern-jacana", "masked-duck"],
  "neotropic-cormorant":         ["least-grebe", "reddish-egret", "tricolored-heron"],
  "northern-jacana":             ["masked-duck", "least-grebe", "black-bellied-whistling-duck"],
  // Ground birds / cuckoos
  "groove-billed-ani":           ["greater-roadrunner", "plain-chachalaca", "green-jay"],
  "greater-roadrunner":          ["groove-billed-ani", "plain-chachalaca", "ferruginous-pygmy-owl"],
  // Thrushes / thrashers / passerines
  "clay-colored-thrush":         ["long-billed-thrasher", "olive-sparrow", "white-tipped-dove"],
  "long-billed-thrasher":        ["clay-colored-thrush", "olive-sparrow", "audubons-oriole"],
  "olive-sparrow":               ["long-billed-thrasher", "white-collared-seedeater", "botteris-sparrow"],
  "white-collared-seedeater":    ["olive-sparrow", "botteris-sparrow", "tropical-parula"],
  "botteris-sparrow":            ["olive-sparrow", "white-collared-seedeater", "clay-colored-thrush"],
  "tropical-parula":             ["white-collared-seedeater", "rose-throated-becard", "olive-sparrow"],
  // Pigeons / doves
  "white-tipped-dove":           ["inca-dove", "red-billed-pigeon", "plain-chachalaca"],
  "inca-dove":                   ["white-tipped-dove", "red-billed-pigeon", "groove-billed-ani"],
  "red-billed-pigeon":           ["white-tipped-dove", "inca-dove", "audubons-oriole"],
  // Parrots
  "green-parakeet":              ["red-crowned-parrot", "groove-billed-ani", "green-jay"],
  "red-crowned-parrot":          ["green-parakeet", "groove-billed-ani", "inca-dove"],
  // Shorebirds
  "american-oystercatcher":      ["piping-plover", "reddish-egret", "mottled-duck"],
  "piping-plover":               ["american-oystercatcher", "mottled-duck", "whooping-crane"],
};
