export const BIRDS_ORDER: { name: string; slug: string }[] = [
  { name: "Green Jay",                     slug: "green-jay" },
  { name: "Altamira Oriole",               slug: "altamira-oriole" },
  { name: "Plain Chachalaca",              slug: "plain-chachalaca" },
  { name: "Buff-bellied Hummingbird",      slug: "buff-bellied-hummingbird" },
  { name: "Painted Bunting",               slug: "painted-bunting" },
  { name: "Roseate Spoonbill",             slug: "roseate-spoonbill" },
  { name: "Whooping Crane",                slug: "whooping-crane" },
  { name: "Crested Caracara",              slug: "crested-caracara" },
  { name: "Harris's Hawk",                 slug: "harriss-hawk" },
  { name: "Aplomado Falcon",               slug: "aplomado-falcon" },
  { name: "Broad-winged Hawk",             slug: "broad-winged-hawk" },
  { name: "Gray Hawk",                     slug: "gray-hawk" },
  { name: "Hook-billed Kite",              slug: "hook-billed-kite" },
  { name: "Ringed Kingfisher",             slug: "ringed-kingfisher" },
  { name: "Green Kingfisher",              slug: "green-kingfisher" },
  { name: "Vermilion Flycatcher",          slug: "vermilion-flycatcher" },
  { name: "Great Kiskadee",               slug: "great-kiskadee" },
  { name: "Tropical Kingbird",             slug: "tropical-kingbird" },
  { name: "Ferruginous Pygmy-Owl",         slug: "ferruginous-pygmy-owl" },
  { name: "Elf Owl",                       slug: "elf-owl" },
  { name: "Least Grebe",                   slug: "least-grebe" },
  { name: "Black-bellied Whistling-Duck",  slug: "black-bellied-whistling-duck" },
  { name: "Masked Duck",                   slug: "masked-duck" },
  { name: "Northern Jacana",               slug: "northern-jacana" },
  { name: "Groove-billed Ani",             slug: "groove-billed-ani" },
  { name: "Clay-colored Thrush",           slug: "clay-colored-thrush" },
  { name: "Long-billed Thrasher",          slug: "long-billed-thrasher" },
  { name: "Audubon's Oriole",              slug: "audubons-oriole" },
  { name: "Olive Sparrow",                 slug: "olive-sparrow" },
  { name: "White-tipped Dove",             slug: "white-tipped-dove" },
  { name: "Reddish Egret",                 slug: "reddish-egret" },
  { name: "Tricolored Heron",              slug: "tricolored-heron" },
  { name: "Neotropic Cormorant",           slug: "neotropic-cormorant" },
  { name: "White-tailed Hawk",             slug: "white-tailed-hawk" },
  { name: "White-tailed Kite",             slug: "white-tailed-kite" },
  { name: "Swallow-tailed Kite",           slug: "swallow-tailed-kite" },
  { name: "Couch's Kingbird",              slug: "couchs-kingbird" },
  { name: "Scissor-tailed Flycatcher",     slug: "scissor-tailed-flycatcher" },
  { name: "Rose-throated Becard",          slug: "rose-throated-becard" },
  { name: "Red-billed Pigeon",             slug: "red-billed-pigeon" },
  { name: "Inca Dove",                     slug: "inca-dove" },
  { name: "Greater Roadrunner",            slug: "greater-roadrunner" },
  { name: "American Oystercatcher",        slug: "american-oystercatcher" },
  { name: "Green Parakeet",                slug: "green-parakeet" },
  { name: "Red-crowned Parrot",            slug: "red-crowned-parrot" },
  { name: "White-collared Seedeater",      slug: "white-collared-seedeater" },
  { name: "Tropical Parula",               slug: "tropical-parula" },
  { name: "Mottled Duck",                  slug: "mottled-duck" },
  { name: "Piping Plover",                 slug: "piping-plover" },
  { name: "Botteri's Sparrow",             slug: "botteris-sparrow" },
];

export const toBirdId = (name: string): string =>
  name.toLowerCase().replace(/[''']/g, "").replace(/[^a-z0-9]+/g, "-").replace(/^-|-$/g, "");
