export const birds = [
  {
    name: "Green Jay",
    scientific: "Cyanocorax yncas",
    family: "Jays & Crows",
    status: "Resident",
    habitat: "Thornscrub, riparian woodland",
    notes: "One of the most sought-after birds in the U.S., found nowhere north of the Rio Grande Valley. Unmistakable with its bright green, blue, and yellow plumage; visits feeders readily.",
    photo: "/images/birds/green-jay-thumb.webp",
  },
  {
    name: "Altamira Oriole",
    scientific: "Icterus gularis",
    family: "Blackbirds & Orioles",
    status: "Resident",
    habitat: "Riparian forest, shade trees",
    notes: "The largest oriole in the U.S., this brilliant orange-and-black bird weaves a distinctive foot-long hanging nest. A reliable feeder visitor at Bentsen SP and Santa Ana NWR.",
    photo: "/images/birds/altamira-oriole-thumb.webp",
  },
  {
    name: "Plain Chachalaca",
    scientific: "Ortalis vetula",
    family: "Chachalacas",
    status: "Resident",
    habitat: "Dense brush, woodland edges",
    notes: "The only member of its tropical family found in the U.S. Groups erupt into deafening choruses at dawn. Commonly seen at feeders throughout the Valley.",
    photo: "/images/birds/plain-chachalaca-thumb.webp",
  },
  {
    name: "Buff-bellied Hummingbird",
    scientific: "Amazilia yucatanensis",
    family: "Hummingbirds",
    status: "Resident",
    habitat: "Woodland edges, gardens",
    notes: "The only hummingbird that regularly breeds in South Texas, identified by its red bill and rufous tail. Unique among U.S. hummingbirds in moving northward after breeding season.",
    photo: "/images/birds/buff-bellied-hummingbird-thumb.webp",
  },
  {
    name: "Painted Bunting",
    scientific: "Passerina ciris",
    family: "Cardinals & Allies",
    status: "Winter visitor / migrant",
    habitat: "Brushy edges, weedy fields, gardens",
    notes: "The male is arguably the most colorful bird in North America — a mosaic of red, blue, and green. Winters in South Texas in good numbers and visits feeders offering millet.",
    photo: "/images/birds/painted-bunting-thumb.webp",
  },
  {
    name: "Roseate Spoonbill",
    scientific: "Platalea ajaja",
    family: "Ibises & Spoonbills",
    status: "Resident",
    habitat: "Shallow coastal bays, resacas, wetlands",
    notes: "A shocking splash of flamingo-pink in the Texas wetlands. Feeds by sweeping its spoon-shaped bill side to side through shallow water. Nests colonially along the coast.",
    photo: "/images/birds/roseate-spoonbill-thumb.webp",
  },
  {
    name: "Whooping Crane",
    scientific: "Grus americana",
    family: "Cranes",
    status: "Winter visitor",
    habitat: "Salt marshes, tidal flats",
    notes: "North America's tallest bird and one of conservation's greatest comeback stories. The entire wild flock winters at Aransas NWR; best viewed from guided boat tours out of Rockport.",
    photo: "/images/birds/whooping-crane-thumb.webp",
  },
  {
    name: "Crested Caracara",
    scientific: "Caracara plancus",
    family: "Falcons",
    status: "Resident",
    habitat: "Open pastures, brushlands, roadsides",
    notes: "A bold, long-legged falcon of open country with a striking black-and-white pattern and bright orange face. Often seen walking on the ground or perched on fence posts and utility poles.",
    photo: "/images/birds/crested-caracara-thumb.webp",
  },
  {
    name: "Harris's Hawk",
    scientific: "Parabuteo unicinctus",
    family: "Hawks, Kites & Allies",
    status: "Resident",
    habitat: "Brushy desert, thornscrub, open woodland",
    notes: "The only hawk in the world known to hunt cooperatively in family groups. Rich chestnut shoulders and thighs contrast with a dark body; a common and charismatic sight across South Texas.",
    photo: "/images/birds/harriss-hawk-thumb.webp",
  },
  {
    name: "Aplomado Falcon",
    scientific: "Falco femoralis",
    family: "Falcons",
    status: "Resident (reintroduced)",
    habitat: "Open coastal prairie, brushy flats",
    notes: "Once extirpated from the U.S., reintroduced at Laguna Atascosa NWR starting in the 1990s. Slender and elegant, with a bold facial pattern; one of the great conservation success stories.",
    photo: "/images/birds/aplomado-falcon-thumb.webp",
  },
  {
    name: "Broad-winged Hawk",
    scientific: "Buteo platypterus",
    family: "Hawks, Kites & Allies",
    status: "Migrant",
    habitat: "Woodland, open skies during migration",
    notes: "Unremarkable for most of the year, but in September the skies above Hazel Bazemore County Park fill with hundreds of thousands streaming south — one of birding's great spectacles.",
    photo: "/images/birds/broad-winged-hawk-thumb.webp",
  },
  {
    name: "Gray Hawk",
    scientific: "Buteo plagiatus",
    family: "Hawks, Kites & Allies",
    status: "Resident",
    habitat: "Riparian woodland along the Rio Grande",
    notes: "A finely gray-barred hawk of the river corridor, reaching the northern edge of its range in the Rio Grande Valley. Its loud, drawn-out call is a characteristic sound of the riparian zone.",
    photo: "/images/birds/gray-hawk-thumb.webp",
  },
  {
    name: "Hook-billed Kite",
    scientific: "Chondrohierax uncinatus",
    family: "Hawks, Kites & Allies",
    status: "Rare resident",
    habitat: "Riparian forest",
    notes: "One of the rarest regularly occurring raptors in the U.S., best looked for soaring over the riparian forest from the hawk watch platform at Bentsen-Rio Grande SP.",
    photo: "/images/birds/hook-billed-kite-thumb.webp",
  },
  {
    name: "Ringed Kingfisher",
    scientific: "Megaceryle torquata",
    family: "Kingfishers",
    status: "Resident",
    habitat: "Rivers, resacas, large water bodies",
    notes: "The largest kingfisher in the Americas, barely reaching the U.S. in South Texas. A noisy, rattling presence along the Rio Grande and its oxbow lakes; much larger than the familiar Belted Kingfisher.",
    photo: "/images/birds/ringed-kingfisher-thumb.webp",
  },
  {
    name: "Green Kingfisher",
    scientific: "Chloroceryle americana",
    family: "Kingfishers",
    status: "Resident",
    habitat: "Clear streams, resacas, irrigation channels",
    notes: "The smallest of the three kingfisher species in the Valley, barely larger than a sparrow. A secretive gem that perches low over clear water, diving for tiny fish.",
    photo: "/images/birds/green-kingfisher-thumb.webp",
  },
  {
    name: "Vermilion Flycatcher",
    scientific: "Pyrocephalus rubinus",
    family: "Tyrant Flycatchers",
    status: "Resident / winter visitor",
    habitat: "Open areas near water, parks, brushy fields",
    notes: "The male's blazing red crown and breast make it one of the most eye-catching birds in Texas. Perches conspicuously on exposed branches and wire fences while hunting insects.",
    photo: "/images/birds/vermilion-flycatcher-thumb.webp",
  },
  {
    name: "Great Kiskadee",
    scientific: "Pitangus sulphuratus",
    family: "Tyrant Flycatchers",
    status: "Resident",
    habitat: "Open woodland, resacas, gardens",
    notes: "Loud, bold, and almost impossible to miss: this yellow-bellied flycatcher announces itself constantly with its namesake \"KISS-ka-dee\" call. One of the most conspicuous birds in any RGV park.",
    photo: "/images/birds/great-kiskadee-thumb.webp",
  },
  {
    name: "Tropical Kingbird",
    scientific: "Tyrannus melancholicus",
    family: "Tyrant Flycatchers",
    status: "Uncommon resident",
    habitat: "Open areas near water, woodland edges",
    notes: "Nearly identical to the more common Couch's Kingbird — the call (a rapid, twittering pip) is the safest way to tell them apart. Look for a notched rather than forked tail.",
    photo: "/images/birds/tropical-kingbird-thumb.webp",
  },
  {
    name: "Ferruginous Pygmy-Owl",
    scientific: "Glaucidium brasilianum",
    family: "Owls",
    status: "Resident",
    habitat: "Dense thornscrub, woodland",
    notes: "Tiny but ferocious, this diurnal owl is a prized find in the Valley's dense brush. It often responds to imitations of its whistle, and draws in scolding songbirds.",
    photo: "/images/birds/ferruginous-pygmy-owl-thumb.webp",
  },
  {
    name: "Elf Owl",
    scientific: "Micrathene whitneyi",
    family: "Owls",
    status: "Summer resident",
    habitat: "Riparian woodland, thornscrub",
    notes: "The world's smallest owl by weight, barely larger than a sparrow. Arrives in spring to nest in old woodpecker cavities; its puppy-like yipping calls reveal it at dusk along the Rio Grande.",
    photo: "/images/birds/elf-owl-thumb.webp",
  },
  {
    name: "Least Grebe",
    scientific: "Tachybaptus dominicus",
    family: "Grebes",
    status: "Resident",
    habitat: "Ponds, resacas, slow streams",
    notes: "The smallest grebe in the Western Hemisphere, barely larger than a tennis ball. Common on resacas and ponds throughout the Valley; golden eyes give it a surprisingly intense expression.",
    photo: "/images/birds/least-grebe-thumb.webp",
  },
  {
    name: "Black-bellied Whistling-Duck",
    scientific: "Dendrocygna autumnalis",
    family: "Ducks",
    status: "Resident",
    habitat: "Ponds, resacas, flooded fields",
    notes: "A colorful, long-necked duck with a candy-orange bill that has dramatically expanded its range into Texas. Often seen in large flocks perched in trees or grazing in grassy fields.",
    photo: "/images/birds/black-bellied-whistling-duck-thumb.webp",
  },
  {
    name: "Masked Duck",
    scientific: "Nomonyx dominicus",
    family: "Ducks",
    status: "Rare resident",
    habitat: "Densely vegetated ponds and resacas",
    notes: "One of the most sought-after rarities in Texas, lurking in thick emergent vegetation. Estero Llano Grande SP is perhaps the most reliable site in the U.S. for this otherwise secretive stiff-tail.",
    photo: "/images/birds/masked-duck-thumb.webp",
  },
  {
    name: "Northern Jacana",
    scientific: "Jacana spinosa",
    family: "Jacanas",
    status: "Rare resident",
    habitat: "Floating vegetation on ponds and resacas",
    notes: "Walks on floating lily pads on absurdly long toes, earning the nickname \"lily-trotter.\" A tropical species that barely reaches the U.S.; Estero Llano Grande SP is the most consistent spot.",
    photo: "/images/birds/northern-jacana-thumb.webp",
  },
  {
    name: "Groove-billed Ani",
    scientific: "Crotophaga sulcirostris",
    family: "Cuckoos",
    status: "Summer resident",
    habitat: "Brushy fields, woodland edges, pastures",
    notes: "A gangly, all-black cuckoo with a bizarre grooved bill and a loose, floppy flight. Moves through low brush in noisy, cooperative family groups; becomes scarce in the Valley by late fall.",
    photo: "/images/birds/groove-billed-ani-thumb.webp",
  },
  {
    name: "Clay-colored Thrush",
    scientific: "Turdus grayi",
    family: "Thrushes",
    status: "Rare resident",
    habitat: "Dense riparian thickets, shaded gardens",
    notes: "The national bird of Costa Rica barely reaches the U.S. in South Texas. Plain brown but a superb singer; a few pairs have established in the Valley, most reliably at Bentsen SP.",
    photo: "/images/birds/clay-colored-thrush-thumb.webp",
  },
  {
    name: "Long-billed Thrasher",
    scientific: "Toxostoma longirostre",
    family: "Mockingbirds & Thrashers",
    status: "Resident",
    habitat: "Dense thornscrub, brushy woodland",
    notes: "A South Texas endemic with a strongly curved bill and rich, varied song. Skulky but vocal; sings persistently from within dense brush in spring and can be drawn to the open with patience.",
    photo: "/images/birds/long-billed-thrasher-thumb.webp",
  },
  {
    name: "Audubon's Oriole",
    scientific: "Icterus graduacauda",
    family: "Blackbirds & Orioles",
    status: "Resident",
    habitat: "Dense thornscrub, riparian thickets",
    notes: "A secretive oriole with a black hood and bright yellow body that rarely ventures to feeders. Heard more often than seen; its rich, slow whistles carry through the brush at Bentsen SP.",
    photo: "/images/birds/audubons-oriole-thumb.webp",
  },
  {
    name: "Olive Sparrow",
    scientific: "Arremonops rufivirgatus",
    family: "New World Sparrows",
    status: "Resident",
    habitat: "Dense thornscrub undergrowth",
    notes: "A drab but characteristic bird of the Valley's dense brush, rarely venturing far from cover. Its dry, accelerating trill is a background sound of any thornscrub walk — but seeing one takes patience.",
    photo: "/images/birds/olive-sparrow-thumb.webp",
  },
  {
    name: "White-tipped Dove",
    scientific: "Leptotila verreauxi",
    family: "Pigeons & Doves",
    status: "Resident",
    habitat: "Dense thornscrub, shaded woodland floor",
    notes: "A plump, ground-hugging dove that walks beneath feeders at Valley nature centers. Its low, hollow hoot — like blowing across the top of a bottle — is one of the signature sounds of the RGV.",
    photo: "/images/birds/white-tipped-dove-thumb.webp",
  },
  {
    name: "Reddish Egret",
    scientific: "Egretta rufescens",
    family: "Herons",
    status: "Resident",
    habitat: "Coastal bays, tidal flats, salt lagoons",
    notes: "Among the rarest herons in North America and a Texas coastal specialty. Feeds with a spectacular lunging, wing-spreading display — sprinting and spinning to startle fish into the open. Occurs in both a dark morph and a scarce white morph.",
    photo: "/images/birds/reddish-egret-thumb.webp",
  },
  {
    name: "Tricolored Heron",
    scientific: "Egretta tricolor",
    family: "Herons",
    status: "Resident",
    habitat: "Coastal marshes, estuaries, resacas",
    notes: "The only U.S. heron with a white belly contrasting sharply against slate-blue upperparts. An agile, fast-running forager that chases prey at a sprint rather than stalking. Common in coastal marshes and tidal flats from Corpus Christi south.",
    photo: "/images/birds/tricolored-heron-thumb.webp",
  },
  {
    name: "Neotropic Cormorant",
    scientific: "Nannopterum brasilianum",
    family: "Cormorants",
    status: "Resident",
    habitat: "Resacas, ponds, rivers, coastal bays",
    notes: "Smaller and longer-tailed than the familiar Double-crested Cormorant, identified by its tan facial skin bordered in white. Abundant at Estero Llano Grande and other Valley resacas; often nests colonially in the same trees as herons and spoonbills.",
    photo: "/images/birds/neotropic-cormorant-thumb.webp",
  },
  {
    name: "White-tailed Hawk",
    scientific: "Geranoaetus albicaudatus",
    family: "Hawks, Kites & Allies",
    status: "Resident",
    habitat: "Coastal prairie, open brushland",
    notes: "A large, striking raptor found in the U.S. only in South Texas. Adults show clean white underparts, rusty shoulder patches, and a white tail with a single narrow black band. Perches prominently on utility poles and fenceposts across the open prairies between Corpus Christi and the coast.",
    photo: "/images/birds/white-tailed-hawk-thumb.webp",
  },
  {
    name: "White-tailed Kite",
    scientific: "Elanus leucurus",
    family: "Hawks, Kites & Allies",
    status: "Resident",
    habitat: "Open grasslands, agricultural fields, roadsides",
    notes: "A ghostly white kite that hunts by hovering in place over open fields — a behavior unique among North American raptors. Black shoulder patches and red eyes give the perched bird a striking look. Often seen on roadsides and near farm fields wherever rodents are plentiful.",
    photo: "/images/birds/white-tailed-kite-thumb.webp",
  },
  {
    name: "Swallow-tailed Kite",
    scientific: "Elanoides forficatus",
    family: "Hawks, Kites & Allies",
    status: "Migrant",
    habitat: "Open sky, woodland edges, river corridors",
    notes: "Arguably the most graceful bird in North America. Migrates through South Texas in spring and fall, often in loose groups, effortlessly banking on its impossibly long forked tail. Watch overhead at Valley hotspots from late April through May and again in August.",
    photo: "/images/birds/swallow-tailed-kite-thumb.webp",
  },
  {
    name: "Couch's Kingbird",
    scientific: "Tyrannus couchii",
    family: "Tyrant Flycatchers",
    status: "Resident",
    habitat: "Woodland edges, roadsides, towns, parks",
    notes: "The default large yellow kingbird of the Rio Grande Valley — nearly identical to the Tropical Kingbird but told by its slightly thicker, forked tail and distinctive call: a rolling, nasal breeeer. Found in almost any park, garden, or open area in the Valley.",
    photo: "/images/birds/couchs-kingbird-thumb.webp",
  },
  {
    name: "Scissor-tailed Flycatcher",
    scientific: "Tyrannus forficatus",
    family: "Tyrant Flycatchers",
    status: "Summer resident",
    habitat: "Open country, pastures, roadsides, fencelines",
    notes: "One of the most eye-catching birds in Texas: a pale gray flycatcher with salmon-pink sides and an extraordinary forked tail that can exceed its own body length. Arrives in spring and is conspicuous on utility wires throughout South Texas. The state bird of Oklahoma.",
    photo: "/images/birds/scissor-tailed-flycatcher-thumb.webp",
  },
  {
    name: "Rose-throated Becard",
    scientific: "Pachyramphus aglaiae",
    family: "Becards",
    status: "Rare resident",
    habitat: "Riparian forest, dense riverside growth",
    notes: "One of the most sought-after rarities in the Rio Grande Valley, barely reaching the U.S. The male's rose-pink throat is stunning against its gray plumage. Builds a large, shaggy ball-shaped nest of grass and plant fiber hanging from a branch tip — the nest is often easier to spot than the bird.",
    photo: "/images/birds/rose-throated-becard-thumb.webp",
  },
  {
    name: "Red-billed Pigeon",
    scientific: "Patagioenas flavirostris",
    family: "Pigeons & Doves",
    status: "Resident",
    habitat: "Riparian forest along the Rio Grande",
    notes: "A large, dark wine-colored pigeon of the river corridor that barely reaches the U.S. in South Texas. Most reliably seen flying over the Rio Grande at dawn from Bentsen SP's hawk watch platform. Its deep, resonant cooing fills the riparian mornings before most other birds have warmed up.",
    photo: "/images/birds/red-billed-pigeon-thumb.webp",
  },
  {
    name: "Inca Dove",
    scientific: "Columbina inca",
    family: "Pigeons & Doves",
    status: "Resident",
    habitat: "Urban parks, gardens, roadsides, feeders",
    notes: "A small, intricately scaly dove of towns and gardens, immediately identified by its squeaky two-note no hope call and the bright rufous wing flash in flight. One of the most common birds at feeders and picnic areas throughout the Valley — easy to overlook, but charming on close inspection.",
    photo: "/images/birds/inca-dove-thumb.webp",
  },
  {
    name: "Greater Roadrunner",
    scientific: "Geococcyx californianus",
    family: "Cuckoos",
    status: "Resident",
    habitat: "Thornscrub, brushy desert, roadsides",
    notes: "The iconic ground-dwelling cuckoo of the Southwest — a fast, fearless predator that takes lizards, snakes, scorpions, and even small birds. More often heard (a series of descending, mournful coos) than seen sprinting across the road. Encountered throughout thornscrub habitats across South Texas.",
    photo: "/images/birds/greater-roadrunner-thumb.webp",
  },
  {
    name: "American Oystercatcher",
    scientific: "Haematopus palliatus",
    family: "Oystercatchers",
    status: "Resident",
    habitat: "Sandy beaches, shell reefs, tidal flats",
    notes: "Unmistakable with its bold black-and-white plumage, massive orange-red bill, and far-carrying piping calls. Pries open oysters and mussels by stabbing its laterally flattened bill into the shell gap. Resident along the Texas coast; the barrier island beaches south of Corpus Christi hold good numbers.",
    photo: "/images/birds/american-oystercatcher-thumb.webp",
  },
  {
    name: "Green Parakeet",
    scientific: "Psittacara holochlorus",
    family: "Parrots",
    status: "Resident (naturalized)",
    habitat: "Urban trees, palm groves, parks",
    notes: "A naturalized population descended from escaped cage birds has established throughout the lower Rio Grande Valley, especially around McAllen. Noisy flocks roost communally in city trees and announce themselves with loud screeching. Considered one of the two naturally-occurring wild parakeets in the continental U.S.",
    photo: "/images/birds/green-parakeet-thumb.webp",
  },
  {
    name: "Red-crowned Parrot",
    scientific: "Amazona viridigenalis",
    family: "Parrots",
    status: "Resident (naturalized)",
    habitat: "Urban neighborhoods, palm trees, orchards",
    notes: "A charismatic bright-green parrot with a scarlet crown established in Brownsville and McAllen. Paradoxically, the feral Texas population now rivals or exceeds the remaining wild birds in Mexico — making the RGV an unexpected stronghold for this critically endangered species.",
    photo: "/images/birds/red-crowned-parrot-thumb.webp",
  },
  {
    name: "White-collared Seedeater",
    scientific: "Sporophila morelleti",
    family: "Seedeaters & Allies",
    status: "Rare resident",
    habitat: "Weedy fields, Carrizo cane, tall grass near the Rio Grande",
    notes: "One of the most sought-after birds on the U.S. list, found only in a narrow stretch along the Rio Grande near Zapata. A tiny, round finch — the male striking in black and white — that lurks in tall weeds and cane. Patient visitors stake out known sites at dawn for the best chance.",
    photo: "/images/birds/white-collared-seedeater-thumb.webp",
  },
  {
    name: "Tropical Parula",
    scientific: "Setophaga pitiayumi",
    family: "Wood-Warblers",
    status: "Rare resident",
    habitat: "Spanish moss-draped oaks, riparian forest",
    notes: "A tiny warbler nearly identical to the Northern Parula but lacking the dark breast band. Rare but regular in the Valley; closely tied to Spanish moss, which it uses as nesting material. Most reliably found at Bentsen SP and Santa Ana NWR in late spring and summer.",
    photo: "/images/birds/tropical-parula-thumb.webp",
  },
  {
    name: "Mottled Duck",
    scientific: "Anas fulvigula",
    family: "Ducks",
    status: "Resident",
    habitat: "Coastal marshes, prairie ponds, bays",
    notes: "The only dabbling duck that breeds year-round along the Gulf Coast. It closely resembles a Mallard but has a bright yellow bill and darker, unmarked plumage; hybridization with feral Mallards is an ongoing conservation concern. Common in coastal marshes from Corpus Christi south.",
    photo: "/images/birds/mottled-duck-thumb.webp",
  },
  {
    name: "Piping Plover",
    scientific: "Charadrius melodus",
    family: "Plovers",
    status: "Winter visitor",
    habitat: "Sandy beaches, tidal flats, shell reefs",
    notes: "One of North America's most endangered shorebirds, but the Texas coast winters a significant share of the global population. Small and pale as dry sand, it blends into the beach almost perfectly. Padre Island National Seashore and the barrier islands of the Coastal Bend are among the most important wintering sites in the country.",
    photo: "/images/birds/piping-plover-thumb.webp",
  },
  {
    name: "Botteri's Sparrow",
    scientific: "Peucaea botterii",
    family: "New World Sparrows",
    status: "Summer resident",
    habitat: "Coastal tallgrass prairie, weedy fields",
    notes: "A nondescript sparrow that arrives in summer specifically to breed in Tamaulipan coastal grasslands. Nearly impossible to find without its song — a series of chips and trills that accelerates into a distinctive bouncing-ball rattle. The Sabal Palm Sanctuary near Brownsville is a reliable site.",
    photo: "/images/birds/botteris-sparrow-thumb.webp",
  },
  {
    name: "Muscovy Duck",
    scientific: "Cairina moschata",
    family: "Ducks",
    status: "Rare resident",
    habitat: "Rio Grande riverbanks and backwaters",
    notes: "Not the warty barnyard bird of city parks — the true wild Muscovy Duck barely reaches the U.S. along the Rio Grande, dark and iridescent with a bold white wing patch. Salineño is by far the most reliable U.S. site, best scanned from the riverbank at dawn.",
    photo: "/images/birds/muscovy-duck-thumb.webp",
  },
];
